In [1]:
#Ans:01

import numpy as np
a= np.arange(start=1, stop=50, step=3)
a


array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [8]:
#Ans:02

import numpy as np
list1=[]
list2=[] 
for i in range(0,5):          # iterating till the range 
    a = int(input("Enter the elements : "))
    list1.append(a)
print(list1)
array1 = np.array(list1)
for e in range(0,5): 
    b = int(input("Enter the elements : "))
    list2.append(b)
print(list2)
array2 = np.array(list2)
c= np.concatenate((array1, array2))
print(c)                      #Concatenating array and printing it
print(np.sort(c))             #Sorting the array and printing it

Enter the elements : 5
Enter the elements : 5
Enter the elements : 3
Enter the elements : 3
Enter the elements : 3
[5, 5, 3, 3, 3]
Enter the elements : 4
Enter the elements : 4
Enter the elements : 7
Enter the elements : 8
Enter the elements : 9
[4, 4, 7, 8, 9]
[5 5 3 3 3 4 4 7 8 9]
[3 3 3 4 4 5 5 7 8 9]


In [11]:
#Ans:03

import numpy as np
arr = np.array( [[ 1, 2, 3], [ 4, 2, 5]] )
print("No. of dimensions: ", arr.ndim)  #Dimension
print("Size of array: ", arr.size)      #Size


No. of dimensions:  2
Size of array:  6


In [13]:
#Ans:04

import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('1D Numpy array:',arr)
arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)


1D Numpy array: [0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [16]:
#Ans: 05

import numpy as np
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3],[4, 4]])
vert= np.vstack((a1, a2))
hori = np.hstack((a1, a2))
print(vert)
print(hori)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]


In [20]:
#Ans: 06

import numpy as np
a = np.array([0, 3, 0, 1, 0, 1, 2, 1, 0, 0, 0, 0, 1, 3, 4])
unique, counts = np.unique(a, return_counts=True)
dict(zip(unique, counts))

{0: 7, 1: 4, 2: 1, 3: 2, 4: 1}